stages:
  - print
  - mr

hello_job:
  stage: print
  script:
    - echo "Hello, GitLab CI!"
    - sleep 30
    - echo "Job Done!"

mr_job:
  stage: mr
  script:
    - echo "This is GitLab Merge Request"
    - sleep 30
    - echo "Job Done!"
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'